torso_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: torso
  joint_speed: 1.0
  motor:
    id: 1
    init: 512
    min: 0
    max: 1023

shoulder_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: shoulder
  joint_speed: 1.0
  motor:
    id: 2
    init: 512
    min: 0
    max: 1023

elbow_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: elbow
  joint_speed: 1.0
  motor:
    id: 3
    init: 512
    min: 0
    max: 1023

wrist_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: wrist
  joint_speed: 1.0
  motor:
    id: 4
    init: 512
    min: 0
    max: 1023

wrist_2_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: wrist_2
  joint_speed: 1.0
  motor:
    id: 5
    init: 512
    min: 0
    max: 1023